name: Commit Stage
on: push

env:
  IMAGE_VERSION_HELP_SERVICE: ${{ github.sha }}

jobs:
  build:
    name: Build and Test (JVM)
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Scan the code vulnerability
        uses: anchore/scan-action@v4
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: true
          severity-cutoff: high
      - name: Upload the vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
  build-native:
    name: Build and Test (GraalVM)
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 21
          cache: gradle
      - name: Scan the code vulnerability
        uses: anchore/scan-action@v4
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: true
          severity-cutoff: high
      - name: Upload the vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          chmod +x gradlew
          ./gradlew nativeBuild
  package:
    name: Package and Publish
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build, build-native ]
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 25
          cache: gradle
      - name: Export env variables to GitHub
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
        with:
          path: '.env'
          export-variables: true
          ensure-exists: true
          keys-case: 'upper'
      - name: Build the container image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage \
          -Pversion=$IMAGE_VERSION_HELP_SERVICE
      - name: Scan OCI the image vulnerability
        uses: anchore/scan-action@v4
        id: scan
        with:
          image: ${{ env.IMAGE_NAME_HELP_SERVICE }}:${{ env.IMAGE_VERSION_HELP_SERVICE }}
          fail-build: false
          severity-cutoff: high
      - name: Upload the vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the container image (Git Commit Hash)
        run: docker push ${{ env.IMAGE_NAME_HELP_SERVICE }}:${{ env.IMAGE_VERSION_HELP_SERVICE }}
      - name: Publish the container image (latest)
        run: |
          docker tag \
              ${{ env.IMAGE_NAME_HELP_SERVICE }}:${{ env.IMAGE_VERSION_HELP_SERVICE }} \
              ${{ env.IMAGE_NAME_HELP_SERVICE }}:latest
          docker push ${{ env.IMAGE_NAME_HELP_SERVICE }}:latest
